-- ============================================================================
-- THE CAROUSEL MAKE — BASE DO BANCO NOVO
-- Aplicar num projeto Supabase NOVO (não no zopgzckurfpvzwzbwudi).
--
-- Princípio de fábrica: a anon key nunca LÊ nada. Tudo que o front web
-- precisa registrar entra por INSERT anônimo; leitura é só autenticada
-- (dashboard) ou service_role (backend). Evita desde o dia 1 o vazamento
-- que tivemos que corrir no projeto da Oração Diária.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. Eventos de analytics
--    Mesma forma da tabela do projeto antigo para o dashboard poder ler os
--    dois projetos com o mesmo código; separa por platform='carousel_web'.
-- ---------------------------------------------------------------------------
create table if not exists public.analytics_events (
  id          bigint generated by default as identity primary key,
  user_id     text,
  anon_id     text,
  event       text not null,
  step        text,
  properties  jsonb not null default '{}'::jsonb,
  app_version text,
  platform    text not null default 'carousel_web',
  created_at  timestamptz not null default now()
);

create index if not exists idx_analytics_events_created
  on public.analytics_events(created_at desc);
create index if not exists idx_analytics_events_platform_created
  on public.analytics_events(platform, created_at desc);
create index if not exists idx_analytics_events_event
  on public.analytics_events(event);

alter table public.analytics_events enable row level security;

-- Escrever: liberado (o app web e a landing registram eventos).
drop policy if exists "analytics_anon_insert" on public.analytics_events;
create policy "analytics_anon_insert"
  on public.analytics_events for insert
  to anon
  with check (true);

-- Ler: NUNCA anônimo. Sem policy de select para anon, por design.
drop policy if exists "analytics_auth_select" on public.analytics_events;
create policy "analytics_auth_select"
  on public.analytics_events for select
  to authenticated
  using (true);

-- ---------------------------------------------------------------------------
-- 2. Waitlist
--    A landing cadastra e-mail; ninguém lê sem estar autenticado.
-- ---------------------------------------------------------------------------
create table if not exists public.waitlist (
  id         bigint generated by default as identity primary key,
  email      text not null unique,
  source     text,
  user_agent text,
  created_at timestamptz not null default now()
);

alter table public.waitlist enable row level security;

drop policy if exists "waitlist_anon_insert" on public.waitlist;
create policy "waitlist_anon_insert"
  on public.waitlist for insert
  to anon
  with check (true);

drop policy if exists "waitlist_anon_select" on public.waitlist;
drop policy if exists "waitlist_auth_select" on public.waitlist;
create policy "waitlist_auth_select"
  on public.waitlist for select
  to authenticated
  using (true);

-- Contagem pública sem expor os e-mails (a landing pode mostrar "N na fila").
create or replace function public.get_waitlist_count()
returns integer
language sql
security definer
set search_path = public
as $$
  select count(*)::integer from public.waitlist;
$$;

revoke all on function public.get_waitlist_count() from anon;
grant execute on function public.get_waitlist_count() to authenticated;

-- ---------------------------------------------------------------------------
-- 3. Projetos salvos do usuário (o "arquivo" do carousel no cloud)
--    Deve ser a base do produto: cada usuário autenticado salva os próprios
--    carrosséis. RLS dono-ou-nada — ninguém vê projeto de ninguém.
-- ---------------------------------------------------------------------------
create table if not exists public.projects (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references auth.users(id) on delete cascade,
  title      text not null default 'Sem título',
  data       jsonb not null default '{}'::jsonb,   -- frames, textos, binds etc.
  thumbnail  text,                                  -- data-url pequeno, opcional
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_projects_user
  on public.projects(user_id, updated_at desc);

alter table public.projects enable row level security;

-- Sem NENHUMA policy para anon: nem insert, nem select, nada.
-- Dono lê e escreve o que é dele.
drop policy if exists "projects_owner_all" on public.projects;
create policy "projects_owner_all"
  on public.projects for all
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- updated_at automático
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_projects_touch on public.projects;
create trigger trg_projects_touch
  before update on public.projects
  for each row execute function public.touch_updated_at();
