-- Tabela Universal de Eventos de Analytics
-- Espelha o schema REAL em produção (projeto zopgzckurfpvzwzbwudi),
-- que é o mesmo consumido por app.js e escrito pelo AnalyticsClient do app iOS.
create table if not exists public.analytics_events (
  id          bigint generated by default as identity primary key,
  user_id     text,
  anon_id     text,
  event       text not null,
  step        text,
  properties  jsonb not null default '{}'::jsonb,
  app_version text,
  platform    text,
  created_at  timestamptz not null default now()
);

-- Índices de alta performance
-- O dashboard lê sempre ordenando por created_at desc com limit.
create index if not exists idx_analytics_events_created on public.analytics_events(created_at desc);
create index if not exists idx_analytics_events_platform_created on public.analytics_events(platform, created_at desc);
create index if not exists idx_analytics_events_event on public.analytics_events(event);

-- RLS: Permite inserção anônima e leitura dos eventos
alter table public.analytics_events enable row level security;

drop policy if exists "anon pode registrar eventos" on public.analytics_events;
create policy "anon pode registrar eventos"
  on public.analytics_events for insert
  to anon
  with check (true);

drop policy if exists "anon pode ler eventos de analytics" on public.analytics_events;
create policy "anon pode ler eventos de analytics"
  on public.analytics_events for select
  to anon
  using (true);

-- Função Segura para Obter Contagem da Waitlist
create or replace function public.get_waitlist_count()
returns integer
language sql
security definer
as $$
  select count(*)::integer from public.waitlist;
$$;

-- NOTA: o seed de eventos fictícios foi removido de propósito.
-- Este arquivo roda contra o projeto de PRODUÇÃO; inserir linhas de exemplo
-- contaminaria os números reais do dashboard.
